/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej.campo3.frm;

import ej.campo3.clases.Lote;
import ej.campo3.clases.TipoSuelo;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;




/**
 *
 * @author Leo
 */
public class frmRegistrarCampos extends javax.swing.JFrame {
    
    private static final String[] COLUMNAS= {"Nro.", "Siperficie" , "Tipo de Suelo"};

    private final ArrayList<Lote> lotes;
    private final ArrayList<TipoSuelo> tSuelos;
    
    private String qNroLote = "";
    private String qSuperficie = "";
    private String qtipoSuelo = "";
    
    /**
     * Creates new form frmRegistrarCampos
     */
    public frmRegistrarCampos() {
        
        lotes = new ArrayList<>();
       
        tSuelos =  new ArrayList<>();
        tSuelos.add(new TipoSuelo("I"));
        tSuelos.add(new TipoSuelo("II"));
        tSuelos.add(new TipoSuelo("III"));
        tSuelos.add(new TipoSuelo("IV"));
        
        
        initComponents();
        
        tblSuelos.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evnt) {
                int i = tblSuelos.getSelectedRow();
                qNroLote= (tblSuelos.getValueAt(i, 0).toString());
                qSuperficie = (tblSuelos.getValueAt(i, 1).toString());
                qtipoSuelo = (tblSuelos.getValueAt(i, 2).toString());
                }
            });

        cmbTipoSuelo.setModel(new DefaultComboBoxModel(tSuelos.toArray()));
        
        txtNombreCampo.setText("Campo 41A carca de la Barranca");
        lblMsj1.setVisible(false);
        lblUsrN.setText("Leonardo");
        // dentro de LOTES
        lblMsj2.setVisible(false);
        txtSuperficieCampo.setText("50");
        txtNroLote.setText("3");
        txtSuperficieLote.setText("20");
        //cmbTipoSuelo
        lblMsj3.setVisible(false);
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel0 = new javax.swing.JPanel();
        jPanel01 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreCampo = new javax.swing.JTextField();
        txtSuperficieCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblMsj1 = new javax.swing.JLabel();
        lblUsrt = new javax.swing.JLabel();
        lblUsrN = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnCancelarRegCmp = new javax.swing.JButton();
        btnRegistrarCampo = new javax.swing.JButton();
        jPanel02 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblMsj3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuelos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtNroLote = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSuperficieLote = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoSuelo = new javax.swing.JComboBox<>();
        lblMsj2 = new javax.swing.JLabel();
        btnAgregarLote = new javax.swing.JButton();
        btnEditarLote = new javax.swing.JButton();
        btnQuitarLote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel01.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Superficie: ");

        txtNombreCampo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombreCampo.setText("Campo");
        txtNombreCampo.setSelectedTextColor(new java.awt.Color(0, 0, 102));
        txtNombreCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCampoActionPerformed(evt);
            }
        });

        txtSuperficieCampo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSuperficieCampo.setText("50");
        txtSuperficieCampo.setSelectedTextColor(new java.awt.Color(0, 0, 102));
        txtSuperficieCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuperficieCampoActionPerformed(evt);
            }
        });

        jLabel3.setText("ha.");

        lblMsj1.setForeground(new java.awt.Color(102, 102, 102));
        lblMsj1.setText("Este nombre ya está en uso");

        lblUsrt.setForeground(new java.awt.Color(102, 102, 102));
        lblUsrt.setText("Usuario:");

        lblUsrN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUsrN.setText("hmurakami");

        javax.swing.GroupLayout jPanel01Layout = new javax.swing.GroupLayout(jPanel01);
        jPanel01.setLayout(jPanel01Layout);
        jPanel01Layout.setHorizontalGroup(
            jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMsj1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblUsrt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsrN)
                .addContainerGap())
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel01Layout.setVerticalGroup(
            jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMsj1)
                    .addGroup(jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsrN)
                        .addComponent(lblUsrt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSuperficieCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelarRegCmp.setText("Cancelar");

        btnRegistrarCampo.setText("Registrar Campo");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(btnCancelarRegCmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarCampo)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarRegCmp)
                    .addComponent(btnRegistrarCampo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel02.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel02.setPreferredSize(new java.awt.Dimension(0, 0));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setText("Lotes");

        lblMsj3.setForeground(new java.awt.Color(102, 102, 102));
        lblMsj3.setText("Este Nro. de Lote ya está en Uso");
        lblMsj3.setToolTipText("");
        lblMsj3.setAlignmentX(0.5F);
        lblMsj3.setMaximumSize(new java.awt.Dimension(200, 20));
        lblMsj3.setMinimumSize(new java.awt.Dimension(200, 20));
        lblMsj3.setPreferredSize(new java.awt.Dimension(200, 20));

        tblSuelos.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tblSuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nro", "Superficie", "Tipo de Suelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSuelos.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        tblSuelos.setRowHeight(20);
        tblSuelos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuelos);
        if (tblSuelos.getColumnModel().getColumnCount() > 0) {
            tblSuelos.getColumnModel().getColumn(0).setMinWidth(70);
            tblSuelos.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblSuelos.getColumnModel().getColumn(0).setMaxWidth(50);
            tblSuelos.getColumnModel().getColumn(1).setPreferredWidth(70);
        }

        jLabel9.setText("Nro.: ");

        txtNroLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNroLote.setText("3");
        txtNroLote.setSelectedTextColor(new java.awt.Color(0, 0, 102));
        txtNroLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroLoteActionPerformed(evt);
            }
        });

        jLabel10.setText("Superficie: ");

        txtSuperficieLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSuperficieLote.setText("50");
        txtSuperficieLote.setSelectedTextColor(new java.awt.Color(0, 0, 102));
        txtSuperficieLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuperficieLoteActionPerformed(evt);
            }
        });

        jLabel11.setText("ha.");

        jLabel12.setText("Tipo de Suelo : ");

        cmbTipoSuelo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblMsj2.setForeground(new java.awt.Color(102, 102, 102));
        lblMsj2.setText("Tenga en cuenta que debe ingresar al menos 1 Lote");
        lblMsj2.setToolTipText("");
        lblMsj2.setAlignmentX(0.5F);
        lblMsj2.setMaximumSize(new java.awt.Dimension(200, 20));
        lblMsj2.setMinimumSize(new java.awt.Dimension(200, 20));
        lblMsj2.setPreferredSize(new java.awt.Dimension(200, 20));

        btnAgregarLote.setText("Agregar Lote");
        btnAgregarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLoteActionPerformed(evt);
            }
        });

        btnEditarLote.setText("Editar");
        btnEditarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLoteActionPerformed(evt);
            }
        });

        btnQuitarLote.setText("Quitar");
        btnQuitarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel02Layout = new javax.swing.GroupLayout(jPanel02);
        jPanel02.setLayout(jPanel02Layout);
        jPanel02Layout.setHorizontalGroup(
            jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel02Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel02Layout.createSequentialGroup()
                        .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel02Layout.createSequentialGroup()
                                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTipoSuelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel02Layout.createSequentialGroup()
                                        .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(jPanel02Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnAgregarLote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarLote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQuitarLote))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel02Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(jPanel02Layout.createSequentialGroup()
                        .addComponent(lblMsj3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(284, 284, 284))))
            .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel02Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lblMsj2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addGap(335, 335, 335)))
        );
        jPanel02Layout.setVerticalGroup(
            jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel02Layout.createSequentialGroup()
                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel02Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel02Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNroLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSuperficieLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMsj3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLote)
                    .addComponent(btnEditarLote)
                    .addComponent(btnQuitarLote))
                .addContainerGap())
            .addGroup(jPanel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel02Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(lblMsj2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel0Layout = new javax.swing.GroupLayout(jPanel0);
        jPanel0.setLayout(jPanel0Layout);
        jPanel0Layout.setHorizontalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel02, 559, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel01, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel0Layout.setVerticalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel01, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel02, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSuperficieCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuperficieCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuperficieCampoActionPerformed

    private void txtNombreCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCampoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreCampoActionPerformed

    private void txtNroLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroLoteActionPerformed

    private void txtSuperficieLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuperficieLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuperficieLoteActionPerformed

    private void btnAgregarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLoteActionPerformed
        // TODO add your handling code here:
        
        //TipoSuelo tsuelo_ =  new TipoSuelo();
        
        //short Sup = Short.parseShort(txtSuperficieLote.getText());
        
        Lote lote = new Lote(txtNroLote.getText(),
                Short.parseShort(txtSuperficieLote.getText()),
                cmbTipoSuelo.toString());
        
        lotes.add(lote);
        
        MostrarLotes();
        
        txtNroLote.setText("");
        txtSuperficieLote.setText("");
        

    }//GEN-LAST:event_btnAgregarLoteActionPerformed

    private void btnQuitarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLoteActionPerformed
        // TODO add your handling code here:
        
        
                
        for (int i = 0; i < lotes.size(); i++) {
            
            if (qNroLote == lotes.get(i).getNroLote()){
                
                lotes.remove(i);
                MostrarLotes();
                break;
            }
        }
        
    }//GEN-LAST:event_btnQuitarLoteActionPerformed

    private void btnEditarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLoteActionPerformed
        // TODO add your handling code here:
        
        tblSuelos.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent evnt) {
                int i = tblSuelos.getSelectedRow();
                txtNroLote.setText(tblSuelos.getValueAt(i, 0).toString());
                txtSuperficieLote.setText(tblSuelos.getValueAt(i, 1).toString());
                qtipoSuelo =(tblSuelos.getValueAt(i, 2).toString());
                }
            });
        
    }//GEN-LAST:event_btnEditarLoteActionPerformed

    private void tblSuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuelosMouseClicked
        // TODO add your handling code here:
        
        tblSuelos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // check if a double click
                 // your code here
                int i = tblSuelos.getSelectedRow();
                txtNroLote.setText(tblSuelos.getValueAt(i, 0).toString());
                txtSuperficieLote.setText(tblSuelos.getValueAt(i, 1).toString());
                qtipoSuelo =(tblSuelos.getValueAt(i, 2).toString());
                }
              }
           });
        
    }//GEN-LAST:event_tblSuelosMouseClicked

    public void MostrarLotes(){
        String lotes_[][]= new String[lotes.size()][3];
        
        for (int i = 0; i < lotes.size(); i++) {
            lotes_[i][0] = lotes.get(i).getNroLote();
            lotes_[i][1] = lotes.get(i).getSuperficieLote().toString();
            lotes_[i][2] = lotes.get(i).gettSuelo();
            
        }
    
        tblSuelos.setModel(new javax.swing.table.DefaultTableModel(
            lotes_,
            new String [] {
                "Nro", "Superficie", "Tipo de Suelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Short.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
 
    }
                
        
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarCampos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLote;
    private javax.swing.JButton btnCancelarRegCmp;
    private javax.swing.JButton btnEditarLote;
    private javax.swing.JButton btnQuitarLote;
    private javax.swing.JButton btnRegistrarCampo;
    private javax.swing.JComboBox<String> cmbTipoSuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel0;
    private javax.swing.JPanel jPanel01;
    private javax.swing.JPanel jPanel02;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMsj1;
    private javax.swing.JLabel lblMsj2;
    private javax.swing.JLabel lblMsj3;
    private javax.swing.JLabel lblUsrN;
    private javax.swing.JLabel lblUsrt;
    private javax.swing.JTable tblSuelos;
    private javax.swing.JTextField txtNombreCampo;
    private javax.swing.JTextField txtNroLote;
    private javax.swing.JTextField txtSuperficieCampo;
    private javax.swing.JTextField txtSuperficieLote;
    // End of variables declaration//GEN-END:variables
}
