/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RegistrarCampo;

import java.awt.List;


/**
 *
 * @author Leo
 */
public class RegistrarCampo extends javax.swing.JFrame {
    private  List<TipoSuelo> tipoSuelo;
    
    /**
     * Creates new form RegistrarCampo
     */
    public RegistrarCampo() {
        tipoSuelo = new ArrayList<>();
        tipoSuelo.add(new NroSuelo("Agua"));
        tipoSuelo.add(new NroSuelo("Granito"));
        tipoSuelo.add(new NroSuelo("Barroso"));
        
        
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCampo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCampo = new javax.swing.JTextPane();
        lblEstaenUso = new javax.swing.JLabel();
        lblSuperficie = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSuperficie = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblUsuarioNom = new javax.swing.JLabel();
        pnlLotes = new javax.swing.JPanel();
        lblLotesTitulo = new javax.swing.JLabel();
        lblEstaenUso1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        lblNro_rta = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSuperficie1 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        lblNro_rta1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSuperficie2 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        lblNro_rta2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAgregarLote = new javax.swing.JButton();
        btnEditarLote = new javax.swing.JButton();
        btnQuitarLote = new javax.swing.JButton();
        btnCancelarRegistrarCampo = new javax.swing.JButton();
        btnRegistrarCampo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCampo.setForeground(new java.awt.Color(102, 102, 102));
        lblCampo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo.setText("Nombre: ");

        txtCampo.setToolTipText("");
        jScrollPane1.setViewportView(txtCampo);
        txtCampo.getAccessibleContext().setAccessibleName("");

        lblEstaenUso.setForeground(new java.awt.Color(102, 102, 102));
        lblEstaenUso.setText("Este nombre ya está en uso.");
        lblEstaenUso.setToolTipText("");

        lblSuperficie.setForeground(new java.awt.Color(102, 102, 102));
        lblSuperficie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSuperficie.setText("Superficie:");
        lblSuperficie.setToolTipText("");

        txtSuperficie.setToolTipText("");
        jScrollPane2.setViewportView(txtSuperficie);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("ha.");
        jLabel4.setToolTipText("");

        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setText("Usuario:");

        lblUsuarioNom.setText("hmurakami");

        pnlLotes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblLotesTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblLotesTitulo.setForeground(new java.awt.Color(0, 51, 204));
        lblLotesTitulo.setText("Lotes");

        lblEstaenUso1.setForeground(new java.awt.Color(102, 102, 102));
        lblEstaenUso1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEstaenUso1.setText("Tenga en cuenta que debe ingresar al menos 1 Lote");
        lblEstaenUso1.setToolTipText("");
        lblEstaenUso1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nro", "Superficie", "Tipo de Suelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLotes.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane3.setViewportView(tblLotes);

        lblNro_rta.setForeground(new java.awt.Color(102, 102, 102));
        lblNro_rta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNro_rta.setText("Tipo de Suelo:");
        lblNro_rta.setToolTipText("");

        txtSuperficie1.setToolTipText("");
        jScrollPane4.setViewportView(txtSuperficie1);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setToolTipText("");

        lblNro_rta1.setForeground(new java.awt.Color(102, 102, 102));
        lblNro_rta1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNro_rta1.setText("Nro.:");
        lblNro_rta1.setToolTipText("");

        txtSuperficie2.setToolTipText("");
        jScrollPane5.setViewportView(txtSuperficie2);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("ha.");
        jLabel6.setToolTipText("");

        lblNro_rta2.setForeground(new java.awt.Color(102, 102, 102));
        lblNro_rta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNro_rta2.setText("Superficie:");
        lblNro_rta2.setToolTipText("");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jComboBox1ComponentAdded(evt);
            }
        });

        btnAgregarLote.setText("Agregar Lote");
        btnAgregarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLoteActionPerformed(evt);
            }
        });

        btnEditarLote.setText("Editar");
        btnEditarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLoteActionPerformed(evt);
            }
        });

        btnQuitarLote.setText("Quitar");
        btnQuitarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLotesLayout = new javax.swing.GroupLayout(pnlLotes);
        pnlLotes.setLayout(pnlLotesLayout);
        pnlLotesLayout.setHorizontalGroup(
            pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLotesLayout.createSequentialGroup()
                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLotesLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLotesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNro_rta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNro_rta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNro_rta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLotesLayout.createSequentialGroup()
                                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAgregarLote))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLotesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarLote)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarLote))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlLotesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLotesTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstaenUso1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(374, 374, 374))
        );
        pnlLotesLayout.setVerticalGroup(
            pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLotesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlLotesLayout.createSequentialGroup()
                        .addComponent(lblLotesTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstaenUso1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLotesLayout.createSequentialGroup()
                                .addComponent(lblNro_rta1)
                                .addGap(14, 14, 14)
                                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lblNro_rta2))
                                .addGap(19, 19, 19)
                                .addComponent(lblNro_rta))
                            .addGroup(pnlLotesLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLote)
                    .addComponent(btnEditarLote)
                    .addComponent(btnQuitarLote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelarRegistrarCampo.setText("Cancelar");
        btnCancelarRegistrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRegistrarCampoActionPerformed(evt);
            }
        });

        btnRegistrarCampo.setText("Registrar Campo");
        btnRegistrarCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuperficie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEstaenUso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUsuarioNom, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelarRegistrarCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarCampo)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCampo, lblSuperficie});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstaenUso)
                        .addComponent(lblUsuario)
                        .addComponent(lblUsuarioNom))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSuperficie))
                .addGap(18, 18, 18)
                .addComponent(pnlLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarRegistrarCampo)
                    .addComponent(btnRegistrarCampo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCampo, lblSuperficie});

        lblSuperficie.getAccessibleContext().setAccessibleName("Superficie");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarLoteActionPerformed

    private void btnQuitarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarLoteActionPerformed

    private void btnCancelarRegistrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRegistrarCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarRegistrarCampoActionPerformed

    private void btnRegistrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarCampoActionPerformed

    private void btnAgregarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarLoteActionPerformed

    private void jComboBox1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBox1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrarCampo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLote;
    private javax.swing.JButton btnCancelarRegistrarCampo;
    private javax.swing.JButton btnEditarLote;
    private javax.swing.JButton btnQuitarLote;
    private javax.swing.JButton btnRegistrarCampo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblEstaenUso;
    private javax.swing.JLabel lblEstaenUso1;
    private javax.swing.JLabel lblLotesTitulo;
    private javax.swing.JLabel lblNro_rta;
    private javax.swing.JLabel lblNro_rta1;
    private javax.swing.JLabel lblNro_rta2;
    private javax.swing.JLabel lblSuperficie;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioNom;
    private javax.swing.JPanel pnlLotes;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextPane txtCampo;
    private javax.swing.JTextPane txtSuperficie;
    private javax.swing.JTextPane txtSuperficie1;
    private javax.swing.JTextPane txtSuperficie2;
    // End of variables declaration//GEN-END:variables
}
